In [1]:
import numpy as np
import pandas as pd

# Task 3

## 1. Create an empty and a full NumPy array?

In [2]:
arr = np.empty(10)
arr

array([4.99803115e-310, 0.00000000e+000, 6.47287710e+170, 1.87424714e-152,
       3.09389978e+169, 3.68575216e+180, 1.09997833e+155, 4.97460740e+180,
       4.44389806e+252, 5.86554735e-320])

In [3]:
arr = np.full(5, 7)
arr

array([7, 7, 7, 7, 7])

## 2. Create a Numpy array filled with all zeros

In [4]:
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

## 3. Create a Numpy array filled with all ones

In [5]:
arr = np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

## 4. Replace NumPy array elements that don’t satisfy a given condition

In [6]:
arr = np.array([1,11,13,12,18,21,97,1011])

In [7]:
newarr = np.where((arr%3==0), arr, arr*3)
newarr

array([   3,   33,   39,   12,   18,   21,  291, 1011])

## 5. Get the maximum value from a matrix

In [8]:
matrix = np.array([[12,21,55],[14,48,74],[69,55,9]])

In [9]:
print(np.max(matrix))

74


# Task 4

In [ ]:
df = pd.read_csv("https://drive.usercontent.google.com/u/1/uc?id=1eNJlwU2nte6Nu2DodGYvbqQySLmWgU7X&export=download")

<ipython-input-2-719d32388d79>:1: DtypeWarning: Columns (4,5,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("https://drive.usercontent.google.com/u/1/uc?id=1eNJlwU2nte6Nu2DodGYvbqQySLmWgU7X&export=download")


In [ ]:
df.drop(0, inplace=True)
df.head()

date   admin1     admin2     market   latitude  longitude  \
1  1994-01-15    Delhi      Delhi      Delhi  28.666667  77.216667   
2  1994-01-15    Delhi      Delhi      Delhi  28.666667  77.216667   
3  1994-01-15    Delhi      Delhi      Delhi  28.666667  77.216667   
4  1994-01-15  Gujarat  Ahmadabad  Ahmedabad  23.033333  72.616667   
5  1994-01-15  Gujarat  Ahmadabad  Ahmedabad  23.033333  72.616667   

             category      commodity unit priceflag pricetype currency price  \
1  cereals and tubers           Rice   KG    actual    Retail      INR   8.0   
2  miscellaneous food          Sugar   KG    actual    Retail      INR  13.5   
3        oil and fats  Oil (mustard)   KG    actual    Retail      INR  31.0   
4  cereals and tubers           Rice   KG    actual    Retail      INR   6.8   
5  cereals and tubers          Wheat   KG    actual    Retail      INR   6.2   

  usdprice  
1    0.255  
2   0.4303  
3    0.988  
4   0.2167  
5   0.1976

## 1. Split a column in Pandas dataframe and get part of it

In [ ]:
d=df['usdprice'].str.split(".", expand=True)
d.head()

0     1
1  0   255
2  0  4303
3  0   988
4  0  2167
5  0  1976

## 2. Return the Index label if some condition is satisfied over a column in Pandas Dataframe

In [ ]:
def Labl(column):
  return df[df[column]=='Delhi'].index

print(Labl('admin1'))

Int64Index([     1,      2,      3,     31,     32,     33,     65,     66,
               109,    110,
            ...
            165913, 165914, 165915, 165916, 165917, 165918, 165919, 165920,
            165921, 165922],
           dtype='int64', length=3531)


## 3. Drop rows from the dataframe based on certain condition applied on a column

In [ ]:
df.drop(Labl('market'), inplace=True)
df

date            admin1     admin2      market   latitude  \
4       1994-01-15           Gujarat  Ahmadabad   Ahmedabad  23.033333   
5       1994-01-15           Gujarat  Ahmadabad   Ahmedabad  23.033333   
6       1994-01-15           Gujarat  Ahmadabad   Ahmedabad  23.033333   
7       1994-01-15           Gujarat  Ahmadabad   Ahmedabad  23.033333   
8       1994-01-15  Himachal Pradesh     Shimla      Shimla  31.103333   
...            ...               ...        ...         ...        ...   
168491  2024-01-15         Rajasthan     Jaipur  North Zone  26.938848   
168492  2024-01-15         Rajasthan     Jaipur  North Zone  26.938848   
168493  2024-01-15         Rajasthan     Jaipur  North Zone  26.938848   
168494  2024-01-15         Rajasthan     Jaipur  North Zone  26.938848   
168495  2024-01-15         Rajasthan     Jaipur  North Zone  26.938848   

        longitude               category        commodity unit priceflag  \
4       72.616667     cereals and tubers             Rice   KG    actual   
5       72.616667     cereals and tubers            Wheat   KG    actual   
6       72.616667     miscellaneous food            Sugar   KG    actual   
7       72.616667           oil and fats    Oil (mustard)   KG    actual   
8       77.172222     cereals and tubers             Rice   KG    actual   
...           ...                    ...              ...  ...       ...   
168491  75.800056           oil and fats    Oil (soybean)   KG    actual   
168492  75.800056           oil and fats  Oil (sunflower)   KG    actual   
168493  75.800056        pulses and nuts          Lentils   KG    actual   
168494  75.800056        pulses and nuts  Lentils (moong)   KG    actual   
168495  75.800056  vegetables and fruits           Onions   KG    actual   

       pricetype currency   price usdprice  
4         Retail      INR     6.8   0.2167  
5         Retail      INR     6.2   0.1976  
6         Retail      INR    13.5   0.4303  
7         Retail      INR    30.0   0.9562  
8         Retail      INR     9.0   0.2869  
...          ...      ...     ...      ...  
168491    Retail      INR  128.47   1.5502  
168492    Retail      INR  152.13   1.8357  
168493    Retail      INR  147.53   1.7802  
168494    Retail      INR  112.64   1.3592  
168495    Retail      INR   35.26   0.4255  

[164964 rows x 14 columns]

# Task 5

## 1. How to get list of parameters name from a function in Python? (example code)

In [ ]:
import inspect

def powers(base, exponent):
	return base**exponent

print(f"Arguments are {inspect.signature(powers)}")


Arguments are (base, exponent)


## 2. How to Print Multiple Arguments in Python? (example code)

In [ ]:
base = 2
exponent = 5
print("Base and exponents are {0} and {1} respectively.".format(base, exponent))

Base and exponents are 2 and 5 respectively.


## 3. Python program to find the power of a number using recursion


In [ ]:
def power(base, exponent):
  if exponent==0:
    return 1
  else:
    return base*power(base, exponent-1)

print(f"Answer = {power(2,5)}")

Answer = 32
