In [92]:
import numpy as np


In [93]:
# 1.Create an empty and full array
# Empty array
nums1=np.empty(9)
nums1

array([3.51e-322, 7.41e-323, 2.17e-322, 8.89e-323, 3.46e-322, 1.38e-322,
       4.40e-322, 2.17e-322, 3.95e-323])

In [94]:
# Full array
nums2=np.full((1,6),23)
nums2

array([[23, 23, 23, 23, 23, 23]])

In [95]:
# 2.Array with all zeroes
numsZeroes=np.zeros((3,3))
numsZeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
# 3.Array with all ones
numsOnes=np.ones((3,3),dtype=int)
numsOnes

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
# 4.Replace numpy array elements that does not follow a given condition

nums5=np.arange(11,38,3).reshape(3,3)
# before replacement
nums5

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [98]:
# Condition :elements divisible by 2
cond=nums5%2==0
# Replacing all the elements which are not divisible by two with nan
nums5=np.where(cond,nums5,np.nan)
nums5

array([[nan, 14., nan],
       [20., nan, 26.],
       [nan, 32., nan]])

In [99]:
# 5.Getting maximum value from a matrix
nums6=np.random.randint(100,size=(3,3))
print(nums6)
# Max value
print("maximum value:",nums6.max())

[[84 68 26]
 [46 73 54]
 [85 86 63]]
maximum value: 86
