In [1]:
import numpy as np

# 1. Create an empty and a full NumPy array?

In [2]:
arr = np.empty(10)
arr

array([4.99803115e-310, 0.00000000e+000, 6.47287710e+170, 1.87424714e-152,
       3.09389978e+169, 3.68575216e+180, 1.09997833e+155, 4.97460740e+180,
       4.44389806e+252, 5.86554735e-320])

In [3]:
arr = np.full(5, 7)
arr

array([7, 7, 7, 7, 7])

# 2. Create a Numpy array filled with all zeros

In [4]:
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

# 3. Create a Numpy array filled with all ones

In [5]:
arr = np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

# 4. Replace NumPy array elements that don’t satisfy a given condition

In [6]:
arr = np.array([1,11,13,12,18,21,97,1011])

In [7]:
newarr = np.where((arr%3==0), arr, arr*3)
newarr

array([   3,   33,   39,   12,   18,   21,  291, 1011])

# 5. Get the maximum value from a matrix

In [8]:
matrix = np.array([[12,21,55],[14,48,74],[69,55,9]])

In [9]:
print(np.max(matrix))

74
